AudioAppBlocklist=
AudioAppBlocklistInvert=false
AudioOutputDevice=alsa_output.pci-0000_03_00.6.analog-stereo
AudioOutputUseDefault=true
AudioVirtualSinkForceMaxValue=true
AutoStartEnabled=true
BenchmarkCacheC0=2.03562e-06;2.93055e-06;5.20966e-06;1.06964e-05;2.05154e-05;4.60759e-05;0.000100152;0.000259464;0.000662585;0.00162317
BenchmarkCacheC1=1.72127e-07;2.83584e-07;5.93654e-07;1.10258e-06;2.40544e-06;4.93438e-06;9.04287e-06;1.94286e-05;4.58922e-05;8.71945e-05
BenchmarkOnBoot=true
EqualizerShowHandles=true
ExecutablePath=/usr/bin/jamesdsp
LastWindowGeometry=AdnQywADAAAAAAAQAAAAIwAAB28AAAQTAAAAEgAAACUAAAdtAAAEEQAAAAAAAAAAB4AAAAASAAAAJQAAB20AAAQR
SetupDone=true
Theme=Adwaita-Dark
ThemeColors=dark
TrayIconMenu=passthrough;menu_preset;separator;show;quit;
